### ISSUE TITLE
Create component for buttons

### ISSUE THREAD

**Issue by leighfall** [Jbridg12/adversarial.js#31]
![image](https://user-images.githubusercontent.com/59845859/156811646-0109deb3-41cc-45f1-8fd1-8712a1d7ba3e.png)

## Subtasks

- [x] Create general component
- [ ] Style with CSS
- [ ] Make responsive version
- [ ] (Optional) Animate such that when one presses it, it looks like the button is pushed in
