### ISSUE TITLE
Create dropdown

### ISSUE THREAD

**Issue by leighfall** [Jbridg12/adversarial.js#33]
![image](https://user-images.githubusercontent.com/59845859/156812297-4636407e-081f-44e1-b530-3f889c1373bc.png)

## Subtasks

- [ ] Create general component
- [ ] Style with CSS
- [ ] Create responsive version
