### ISSUE TITLE
Create Accordion Component for FAQ

### ISSUE THREAD

**Issue by leighfall** [Jbridg12/adversarial.js#7]
![image](https://user-images.githubusercontent.com/59845859/156811123-38071227-2d6f-4d96-8e6e-cba69cc5e0cd.png)
![image](https://user-images.githubusercontent.com/59845859/156811479-0a5bb15c-95ed-42c2-92d4-db057871d35f.png)

## Subtasks

- [ ] Build component functionality
- [ ] Style with CSS
- [ ] Create responsive version with media query for mobile
